<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.Process'))\Mod.props" />

    <ItemGroup>
        <Reference Include="Colossal.Logging">
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>
